
//  GETS APPLE DAILY DATA
GET /v2/aggs/ticker/AAPL/range/1/day/2025-04-15/2025-04-15 HTTP/1.1
Host: api.polygon.io
Authorization: Bearer ujZYW74TVWrNPncWiPEsHNnjHFrqELwb


//  GETS APPLE DAILY DATA

